server:
  port: 4001

# git配置
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leedan/mybolg
          search-paths: tree/master/config-server/src/main/resources
          username: 1217372812@qq.com
          password: 1991623lidan
  profiles:
    active: active
